# Generated by Django 2.1 on 2018-08-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt3', '0002_auto_20180825_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='join',
            field=models.ManyToManyField(related_name='joiner', to='belt3.User'),
        ),
    ]
